name: number_to_words
description: Convert number into words by localeID
version: 0.1.0
author: Benjith Kizhisseri<mpbenjith@gmail.com>
homepage: https://github.com/Benjith/NumberToWords

environment:
  sdk: '>=2.12.0 <3.0.0'



dev_dependencies:
  flutter_test:
    sdk: flutter
    

